export const brandsData = [
  { name: 'Sony' },
  { name: 'Samsung' },
  { name: 'LG' },
  { name: 'Apple' },
  { name: 'Microsoft' },
  { name: 'Panasonic' },
  { name: 'Toshiba' },
  { name: 'Lenovo' },
  { name: 'Dell' },
  { name: 'HP' },
  { name: 'Asus' },
  { name: 'Acer' },
  { name: 'Nikon' },
  { name: 'Canon' },
  { name: 'GoPro' },
  { name: 'JBL' },
  { name: 'Bose' },
  { name: 'Beats' },
  { name: 'Sonos' },
  { name: 'Razer' },
];
